### ISSUE TITLE
use latest commonmark

### ISSUE THREAD

**Issue by pekeler** [AVGP/susi#6]
Susi uses commonmark 0.12. The current version is 0.25.1 with tons of changes (https://github.com/jgm/commonmark.js/blob/master/changelog.txt).

The 0.12 version is buggy for:

```
hi
---fun---
there
```

**Comment by AVGP** [comment]
Hey Christian,

Thanks for your input on this one. I agree and it's good to know that SuSi
is prone to bugs like this due to commonmark right now.
I would love to see a pull request for this - if you're unsure how to do
that, I'm happy to help - but you'd do me a great favour if you would
submit a pull request for this one :-)

Cheers,
Martin

2016-06-23 0:14 GMT+02:00 Christian Pekeler <notifications@github.com>:

**Comment by AVGP** [comment]
Thanks, Christian!
